/**
 * Emit the built HTML shell into `api/_shell.ts` so the server-side renderer can
 * serve it with per-URL <head> tags baked in.
 *
 * The renderer needs the *built* shell, not the source index.html, because Vite
 * rewrites the script/stylesheet hrefs to hashed filenames on every build.
 * Serving a stale shell means serving links to assets that no longer exist — a
 * blank page — so this runs as part of `npm run build`, never by hand.
 *
 * It also removes the static <title> and <meta name="description"> and leaves a
 * single marker in their place. The renderer then does one string replace on
 * that marker rather than pattern-matching HTML: there is exactly one insertion
 * point, it either exists or the build fails loudly here, and no regex ever
 * runs over a document containing seller-controlled text.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const distIndex = path.resolve(here, "../dist/index.html");
const apiDir = path.resolve(here, "../../api");
const outFile = path.join(apiDir, "_shell.ts");
const seoSrc = path.resolve(here, "../src/lib/seo.ts");
const seoOut = path.join(apiDir, "_seo.ts");

export const MARKER = "<!--PULSESHOP_SEO-->";

/**
 * Where api/render.ts injects prerendered page content.
 *
 * Inside #root, not beside it. main.tsx mounts with createRoot().render(),
 * which clears the container's children on its first commit — so anything put
 * here is shown to a crawler and to a human waiting on the bundle, and is then
 * removed by React itself with no cleanup code and no chance of it lingering
 * behind the real UI.
 */
export const BODY_MARKER = "<!--PULSESHOP_BODY-->";

let html = readFileSync(distIndex, "utf8");

const before = html;
html = html
  .replace(/\n?\s*<title>[\s\S]*?<\/title>/i, "")
  .replace(/\n?\s*<meta\s+name="description"[^>]*>/i, "");

if (html === before) {
  throw new Error(
    "emit-shell: neither <title> nor <meta name=description> was found in dist/index.html — " +
      "the shell layout changed and the renderer would emit duplicate tags.",
  );
}

if (!html.includes("</head>")) {
  throw new Error("emit-shell: no </head> in dist/index.html; nowhere to insert meta tags.");
}
// Leading newline because Vite's PWA plugin injects <link rel="manifest">
// immediately before </head> with no line break of its own, which would
// otherwise leave the <title> sharing a line with it.
html = html.replace("</head>", `\n    ${MARKER}\n  </head>`);

// A build that produced no hashed entry script is broken in a way that would
// only show up as a white page in production.
if (!/<script[^>]+src="\/assets\/[^"]+\.js"/.test(html)) {
  throw new Error("emit-shell: dist/index.html has no hashed /assets entry script.");
}

// The prerender insertion point. Asserted rather than pattern-matched for the
// same reason as MARKER: one exact literal that either survives Vite's
// transform or fails the build here, instead of a regex discovering at runtime
// that the container is now <div id="root" class="...">.
const ROOT = '<div id="root"></div>';
if (!html.includes(ROOT)) {
  throw new Error(
    `emit-shell: dist/index.html has no exact \`${ROOT}\` — the mount point changed, ` +
      "and api/render.ts would ship pages with no crawlable content.",
  );
}
html = html.replace(ROOT, `<div id="root">${BODY_MARKER}</div>`);

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `// GENERATED by frontend/scripts/emit-shell.mjs during \`npm run build\`.
// Do not edit. Regenerated on every build so the asset hashes below always
// match the deployed bundle.
/* eslint-disable */
export const SHELL_MARKER = ${JSON.stringify(MARKER)};
export const SHELL_BODY_MARKER = ${JSON.stringify(BODY_MARKER)};
export const SHELL_BUILT_AT = ${JSON.stringify(new Date().toISOString())};
export const SHELL = ${JSON.stringify(html)};
`,
  "utf8",
);

/**
 * Copy the shared SEO module next to the function instead of having api/
 * reach across into frontend/src.
 *
 * frontend/package.json declares `"type": "module"`, so an import that crosses
 * that boundary resolves under different rules than one inside api/ — and which
 * rules apply depends on whether Vercel's function bundler or Node itself does
 * the resolving. A generated copy sidesteps the question entirely. seo.ts stays
 * the single source of truth; this file is derived from it on every build and
 * is never edited by hand.
 */
const seo = readFileSync(seoSrc, "utf8");
if (/^\s*import\s/m.test(seo)) {
  throw new Error(
    "emit-shell: src/lib/seo.ts has grown an import. It is copied into the " +
      "serverless bundle and must stay dependency-free.",
  );
}
writeFileSync(
  seoOut,
  `// GENERATED from frontend/src/lib/seo.ts by frontend/scripts/emit-shell.mjs.\n` +
    `// Do not edit — edit the original.\n/* eslint-disable */\n${seo}`,
  "utf8",
);

console.log(
  `emit-shell: wrote ${path.relative(process.cwd(), outFile)} (${html.length} bytes) and _seo.ts`,
);
