/**
 * Server-side rendering of PulseShop's public pages — <head> for every URL,
 * and real content for the two that carry the long tail.
 *
 * THE PROBLEM THIS SOLVES. PulseShop is a Vite SPA behind a catch-all rewrite,
 * so until now every URL on the domain served byte-identical HTML with one
 * hardcoded `<title>PulseShop</title>`. Googlebot renders JavaScript and would
 * eventually see more, slowly and unreliably. WhatsApp, Instagram, Facebook and
 * Twitter do not render anything — they read the raw bytes. Since the way
 * PulseShop actually spreads is sellers pasting links into WhatsApp, every
 * shared product was previewing as the generic app blurb.
 *
 * WHAT IT DOES. Serves the built SPA shell with a real <head> for the URL: a
 * per-page title, description, canonical, Open Graph/Twitter card and JSON-LD.
 *
 * Storefronts and product pages additionally get their content prerendered into
 * #root by _prerender.ts. That closed the gap the head alone could not: an
 * empty body has no <a href> in it, so the site had no internal link graph at
 * all — sitemaps got URLs discovered, but nothing on the domain could pass
 * anchor text or authority to anything else on it. It also stops being a bet on
 * Googlebot's render queue, which Bing and the AI answer crawlers do not have
 * an equivalent of.
 *
 * Still not a framework migration and still not hydration: main.tsx uses
 * createRoot().render(), which clears #root on its first commit, so React
 * discards this markup and takes over exactly as before. The prerendered block
 * is therefore also the app's loading state, which on a Kenyan mobile
 * connection replaces several seconds of blank white with the shop's name,
 * banner and products.
 *
 * SECURITY POSTURE.
 *  - Reads with the ANON key only, never service_role. RLS stays the boundary;
 *    a mistake in this file cannot reach data a browser could not already read.
 *  - Reads through the seo_* RPCs (migration 0028), which return an explicit
 *    field list. No `select *` — so the seller's WhatsApp/Instagram/Facebook
 *    contacts, and any column added later, cannot leak into indexable markup.
 *  - Every interpolated value is escaped by lib/seo.ts. This is the app's first
 *    raw-HTML path; React's automatic escaping does not apply here.
 *  - Forwards no request header, cookie or token to Supabase. The response for
 *    a given URL is identical for every visitor, which is what makes it safe to
 *    cache on a shared CDN.
 *  - Anything not recognised as a public page is served noindex, with the
 *    header as well as the meta tag.
 */
// Both generated by frontend/scripts/emit-shell.mjs during `npm run build`.
// _seo.ts is a verbatim copy of frontend/src/lib/seo.ts — edit that one.
import { SHELL, SHELL_BODY_MARKER, SHELL_MARKER } from "./_shell";
import { renderCategoryBody, renderProductBody, renderShopBody } from "./_prerender";
import {
  type PageSeo,
  type SeoCategory,
  type SeoProduct,
  type SeoShop,
  aboutSeo,
  categorySeo,
  faqSeo,
  homeSeo,
  isValidSlug,
  pricesSeo,
  privateSeo,
  productSeo,
  renderHead,
  shopSeo,
  shopsSeo,
  welcomeSeo,
} from "./_seo";

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || "";
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || "";

/**
 * Reserved first path segments — everything the SPA routes itself.
 *
 * `/:shopSlug` is the last route in main.tsx, so any single segment that is not
 * one of these is a shop handle. Kept in sync with main.tsx by the test in
 * scripts/check-seo-routes.mjs, which fails the build if a route is added there
 * and not here — otherwise a new `/wishlist` page would be looked up as a shop,
 * miss, and be served as a 404.
 */
const RESERVED = new Set([
  "shop", "shops", "product", "cart", "checkout", "order", "orders", "account",
  "favorites", "login", "signup", "welcome", "auth", "reset-password",
  "dashboard", "dev", "api", "assets", "icons", "prices", "about", "faq",
  "admindev", "s", "g", "category", "earlyaccessform",
]);

/** Pages that exist for a signed-in human and must never be indexed. */
const PRIVATE_ROOTS = new Set([
  "cart", "checkout", "order", "orders", "account", "favorites", "login",
  "signup", "auth", "reset-password", "dashboard", "dev", "shop", "admindev",
  // A public lead-capture form, not a page anyone should reach from search —
  // it is shared as a direct link (pulseshop.space/earlyaccessform). Served as
  // a noindex 200 so it works when visited but never competes in results.
  "earlyaccessform",
  // /s/CODE is a doorway that immediately replaces itself with the real
  // product page (migration 0052). Indexing it would put a redirect in the
  // results where the product belongs, and would have a crawler scoring
  // clicks against sellers' share links.
  "s",
  // /g/CODE is a live group buy whose whole distribution is people forwarding
  // the link to each other. Indexing it would put a half-filled group with a
  // deadline on it into search results long after that deadline passed.
  "g",
]);

// ---------------------------------------------------------------------------
// The HTML shell
// ---------------------------------------------------------------------------

/**
 * `_shell.ts` is written by frontend/scripts/emit-shell.mjs during the build,
 * and it carries the HASHED asset filenames Vite produced. If it were ever
 * stale, every page on the site would link to JavaScript that no longer exists
 * — a blank page everywhere, with nothing in the logs. It is regenerated on
 * every build, but that relies on Vercel bundling this function AFTER running
 * buildCommand, which is an assumption about someone else's build pipeline.
 *
 * So don't assume. On first use, read the deployment's own /index.html — a real
 * static file, and rewrites only apply on a filesystem miss, so this never
 * routes back here — and derive the shell from that. Whatever the build
 * pipeline did, those are by definition the assets actually being served. The
 * compiled-in copy stays as the fallback if the fetch fails. Memoised per
 * instance, so it costs one request per cold start.
 */
let shellPromise: Promise<string> | null = null;

function withMarker(html: string): string | null {
  if (!html.includes("</head>")) return null;
  const stripped = html
    .replace(/\n?\s*<title>[\s\S]*?<\/title>/i, "")
    .replace(/\n?\s*<meta\s+name="description"[^>]*>/i, "");
  return (
    stripped
      .replace("</head>", `\n    ${SHELL_MARKER}\n  </head>`)
      // Mirrors what emit-shell.mjs does at build time. Best-effort here rather
      // than fatal: this path only runs when the compiled shell might be stale,
      // and a page with correct meta tags but no prerendered body is a far
      // better failure than no page. renderBody's marker replace is a no-op if
      // the literal was not found.
      .replace('<div id="root"></div>', `<div id="root">${SHELL_BODY_MARKER}</div>`)
  );
}

/**
 * Where to fetch our own /index.html from.
 *
 * Deliberately the CANONICAL origin — which is derived from an allowlist, not
 * from the Host header — and never the raw request host. Fetching the shell
 * from a host the client chose would let anyone with a spoofed Host serve their
 * own HTML through our function, on our domain, past our CSP. That is a content
 * injection hole dressed up as a convenience.
 *
 * SHELL_ORIGIN exists so a local harness can point this at itself; unset in
 * production.
 */
const shellOrigin = (canonicalOrigin: string) => process.env.SHELL_ORIGIN || canonicalOrigin;

async function getShell(canonicalOrigin: string): Promise<string> {
  const origin = shellOrigin(canonicalOrigin);
  if (!shellPromise) {
    shellPromise = (async () => {
      try {
        const res = await fetch(`${origin}/index.html`, {
          headers: { "x-pulseshop-shell": "1" },
          signal: AbortSignal.timeout(2000),
        });
        if (res.ok) {
          const marked = withMarker(await res.text());
          if (marked?.includes(SHELL_MARKER)) return marked;
        }
      } catch {
        /* fall through to the build-time copy */
      }
      return SHELL;
    })();
  }
  return shellPromise;
}

// ---------------------------------------------------------------------------
// Supabase
// ---------------------------------------------------------------------------

/**
 * Call a Postgres function over PostgREST.
 *
 * Deliberately plain `fetch` rather than @supabase/supabase-js: this function
 * needs one unauthenticated RPC call, and pulling the SDK in would add a
 * dependency (and its transitive tree) to a bundle that sits on the critical
 * path of every crawler request and every link preview. Fewer moving parts on a
 * public, unauthenticated endpoint is the security argument as much as the cold
 * start one.
 */
async function rpc<T>(fn: string, args: Record<string, unknown>): Promise<T | null> {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) return null;

  // A crawler waiting on us is a crawler we are teaching that the site is slow.
  // Better to serve the generic shell than to hang.
  const abort = AbortSignal.timeout(2500);

  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`, {
      method: "POST",
      headers: {
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify(args),
      signal: abort,
    });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Routing
// ---------------------------------------------------------------------------

/** Shape-check before the round trip: PostgREST would reject a non-uuid anyway,
 * but a bad path should not cost a database call. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * `status` matters for more than tidiness. A missing shop answered with 200 is
 * a soft 404: the crawler is told the page exists, indexes an empty
 * "Shop not found" screen, and every typo'd handle anyone ever links to becomes
 * a thin page on the domain. 404 is the only answer that removes it.
 *
 * Reserved app routes are different — /cart really does exist, it is simply not
 * for crawlers — so those stay 200 with noindex.
 */
type Resolution =
  | {
      kind: "page";
      seo: PageSeo;
      status?: number;
      body?: string;
      /**
       * Whether this response is the same for everybody, and so safe on a
       * shared cache.
       *
       * Defaults to `seo.robots`, which used to be the whole test — every
       * noindex page was a signed-in person's page. A thin category is the
       * first thing that is noindex and still completely public: identical for
       * every visitor, carrying nobody's data, just not worth putting in the
       * index yet. Sending it `private, no-store` would make the site's
       * cheapest pages its slowest for no reason.
       */
      publicPage?: boolean;
    }
  | { kind: "redirect"; to: string };

const notFound = (): Resolution => ({ kind: "page", seo: privateSeo(), status: 404 });

async function resolve(pathname: string, origin: string): Promise<Resolution> {
  const segments = pathname.split("/").filter(Boolean);

  if (segments.length === 0) return { kind: "page", seo: homeSeo(origin) };

  const [first, second] = segments;

  if (first === "shops" && segments.length === 1) {
    return { kind: "page", seo: shopsSeo(origin) };
  }

  // Marketing pages — public and indexable, unlike the rest of RESERVED.
  if (segments.length === 1) {
    if (first === "prices") return { kind: "page", seo: pricesSeo(origin) };
    if (first === "about") return { kind: "page", seo: aboutSeo(origin) };
    if (first === "faq") return { kind: "page", seo: faqSeo(origin) };
    if (first === "welcome") return { kind: "page", seo: welcomeSeo(origin) };
  }

  /**
   * Legacy `/product/<uuid>`. These are already in WhatsApp threads, order
   * confirmations and browser histories, so they keep working — but they
   * redirect to the canonical slug URL rather than rendering a second indexable
   * copy of the same product. Two URLs serving one product is the duplicate
   * content problem the canonical tag exists to solve; a 301 solves it better,
   * and passes on any ranking the old URL had accrued.
   */
  if (first === "product" && second) {
    if (!UUID_RE.test(second)) return notFound();
    const legacy = await rpc<{ handle: string; slug: string }[]>("seo_product_url_by_id", {
      p_id: second,
    });
    const row = Array.isArray(legacy) ? legacy[0] : null;
    if (row?.handle && row?.slug) {
      return { kind: "redirect", to: `${origin}/${row.handle}/${row.slug}` };
    }
    return notFound();
  }

  /**
   * /category/:slug (migration 0056).
   *
   * A real 404 for a slug nothing stocks, not a 200 with an empty grid. Category
   * slugs are guessable — the taxonomy is public in lib/constants.ts — so a
   * soft 404 here would let anyone mint arbitrary thin pages on the domain just
   * by linking at them.
   *
   * Whether a category that DOES exist gets indexed is categorySeo's call, not
   * this one's: it goes noindex under CATEGORY_MIN_PRODUCTS listings. The page
   * still renders for the shopper who filtered into it.
   */
  if (first === "category") {
    if (segments.length !== 2 || !isValidSlug(second)) return notFound();
    const category = await rpc<SeoCategory | null>("seo_category", { p_slug: second });
    return category?.name
      ? {
          kind: "page",
          seo: categorySeo(category, origin),
          body: renderCategoryBody(category),
          publicPage: true,
        }
      : notFound();
  }

  if (PRIVATE_ROOTS.has(first)) return { kind: "page", seo: privateSeo() };
  if (RESERVED.has(first)) return { kind: "page", seo: privateSeo() };

  // /:shopSlug
  if (segments.length === 1) {
    if (!isValidSlug(first)) return notFound();
    const shop = await rpc<SeoShop | null>("seo_shop", { p_handle: first });
    return shop
      ? { kind: "page", seo: shopSeo(shop, origin), body: renderShopBody(shop) }
      : notFound();
  }

  // /:shopSlug/:productSlug
  if (segments.length === 2) {
    if (!isValidSlug(first) || !isValidSlug(second)) return notFound();
    const product = await rpc<SeoProduct | null>("seo_product", {
      p_handle: first,
      p_slug: second,
    });
    return product
      ? { kind: "page", seo: productSeo(product, origin), body: renderProductBody(product) }
      : notFound();
  }

  return notFound();
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

async function handler(request: Request): Promise<Response> {
  const url = new URL(request.url);

  /**
   * Canonical origin.
   *
   * Taken from the request, not from a header a client controls, and pinned to
   * https. Reflecting an attacker-supplied Host into <link rel="canonical"> is
   * how a crawler gets told the real page lives on someone else's domain, so
   * anything that does not look like one of ours falls back to the configured
   * production origin.
   */
  const host = url.host;
  const origin =
    /^([a-z0-9-]+\.)*pulseshop\.space$/i.test(host) || /\.vercel\.app$/i.test(host)
      ? `https://${host}`
      : "https://pulseshop.space";

  if (request.method !== "GET" && request.method !== "HEAD") {
    return new Response("Method Not Allowed", { status: 405, headers: { Allow: "GET, HEAD" } });
  }

  // Our own shell fetch should never reach this function — /index.html is a
  // real file and rewrites only fire on a filesystem miss. If routing ever
  // changes so that it does, answer immediately rather than recursing.
  if (request.headers.get("x-pulseshop-shell")) {
    return new Response(SHELL, {
      status: 200,
      headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" },
    });
  }

  const resolution = await resolve(url.pathname, origin);

  if (resolution.kind === "redirect") {
    return new Response(null, {
      status: 301,
      headers: {
        Location: resolution.to + url.search,
        "Cache-Control": "public, max-age=0, s-maxage=86400",
      },
    });
  }

  const { seo, status = 200, body = "", publicPage = seo.robots } = resolution;
  const html = (await getShell(origin))
    .replace(SHELL_MARKER, renderHead(seo))
    // Pages with no prerendered body (the marketing pages, everything private)
    // clear the marker to the empty string and get exactly the shell they got
    // before. The comment must not survive into the response: it is inside
    // #root, so leaving it there would put a PulseShop-internal token in the
    // markup of every page for no reason.
    .replace(SHELL_BODY_MARKER, body);

  return new Response(request.method === "HEAD" ? null : html, {
    status,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      // Public pages are identical for everyone, so they cache at the edge.
      // Everything else is a page a signed-in person is looking at; even though
      // this response carries none of their data, `private, no-store` keeps a
      // shared cache from ever holding a URL that identifies one user's
      // activity.
      "Cache-Control": publicPage
        ? "public, max-age=0, s-maxage=600, stale-while-revalidate=86400"
        : "private, no-store",
      // Stronger than the meta tag and honoured even for non-HTML fetches.
      ...(seo.robots ? {} : { "X-Robots-Tag": "noindex, nofollow" }),
      // The response varies only by path, never by who is asking. Stated
      // explicitly so no intermediary invents a Vary of its own.
      Vary: "Accept-Encoding",
    },
  });
}

/**
 * Exported as an object with a `fetch` method, NOT as a bare default function.
 *
 * That distinction is load-bearing and cost this site an outage. Vercel's Node
 * runtime reads a bare `export default function(...)` as the legacy Node
 * handler and calls it with `(req, res)`. This function is written against the
 * Web standard, so under that calling convention `new URL(request.url)` throws
 * on a relative path, `request.headers.get` is not a function, and the Response
 * it returns is discarded because nothing ever calls `res.end()`. The symptom
 * is every route either hanging until timeout or answering 500, with a build
 * that passed and logs that show nothing wrong.
 *
 * The object-with-fetch form is what tells the runtime this is a Web handler.
 * See https://vercel.com/docs/functions/runtimes/node-js. Do not "simplify"
 * this back into `export default async function handler`.
 */
export default { fetch: handler };
